name: Snyk scan

on:
  workflow_dispatch:  # Manual trigger for the workflow

permissions:
  id-token: write
  contents: read    
  issues: write
  security-events: write
  actions: read  

jobs:
  # Job for running Snyk to check dependencies for vulnerabilities
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Using a stable version

      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/node@master
        continue-on-error: true
        with: 
          command: test
          args: --sarif-file-output=snyk_dependency_scan.sarif --severity-threshold=low
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Dependency Scan Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_dependency_scan.sarif
