name: Snyk full scan

on:
  workflow_dispatch:  # Manual trigger for the workflow

permissions:
  id-token: write
  contents: read    
  issues: write
  security-events: write
  actions: read  

jobs:
  # Job for running Snyk to check dependencies for vulnerabilities
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Using a stable version

      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/node@master
        continue-on-error: true
        with: 
          command: test
          args: --project-name="trustfactors/origination-admin-portal" --sarif-file-output=snyk_dependency_scan.sarif --severity-threshold=low
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Dependency Scan Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_dependency_scan.sarif

  # Job for running Snyk to check source code for vulnerabilities
  code_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Optionally add path to checkout to a specific subdirectory
        # with:
        #   path: some-subfolder

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: List files in the directory
        run: ls -la ./Code/routes
        
      - name: Run Snyk to check for vulnerabilities in the frontend directory
        uses: snyk/actions/node@master
        continue-on-error: true
        with: 
          command: code test
          args: --sarif-file-output=snyk_code_scan.sarif --severity-threshold=high --path=./Code/routes
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF file to GitHub Security tab
        if: success() || failure() # Upload even if Snyk finds issues
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_code_scan.sarif
